#ifndef SIMCL_TOKENS_H
#define SIMCL_TOKENS_H

typedef enum {
    TOKEN_EOF = 0,
    TOKEN_IDENTIFIER,
    TOKEN_NUMBER,
    TOKEN_STRING,
    TOKEN_LET,
    TOKEN_FUNCTION,
    TOKEN_SIMULATE,
    TOKEN_RETURN,
    TOKEN_WHILE,
    TOKEN_LBRACE,
    TOKEN_RBRACE,
    TOKEN_LPAREN,
    TOKEN_RPAREN,
    TOKEN_PLUS,
    TOKEN_MINUS,
    TOKEN_STAR,
    TOKEN_SLASH,
    TOKEN_EQUAL,
    TOKEN_LT,
    TOKEN_GT,
    TOKEN_COMMA,
    TOKEN_UNKNOWN
} TokenType;

#endif
